### ISSUE TITLE
please help to solve

### ISSUE THREAD

**Issue by mrzeeshanplus** [q2apro/q2apro-newsletter-favtags#1]
A Question2Answer database query failed when generating this page.

A full description of the failure is available in the web server's error log file.

**Comment by q2apro** [comment]
Fixed:
https://github.com/q2apro/q2apro-newsletter-favtags/commit/b3ff7cfecbaf421c863d652933c28ecd43a81d3b
https://github.com/q2apro/q2apro-newsletter-favtags/commit/36c7c6449e0273fae0e776fb454158db85b72773
